import type { InferGetServerSidePropsType, GetServerSideProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';

export const getServerSideProps = (async () => {
	// const result = await fetch('https://api.example.com/data');

	return {
		props: {
			message: 'Hello, world!',
		},
	};
}) satisfies GetServerSideProps<{ message: string }>;

export default function Hello({
	message,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
	return (
		<>
			<Head>
				<title>Another page to say hello to user</title>
				<meta
					name="description"
					content="Generated by create next app, using page routing approach."
				/>
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section>
				<h1>Message coming from the server</h1>
				<p>{message}</p>
				<Link href="/">Go back home</Link>
			</section>
		</>
	);
}
